spring:
  application:
    name: digi-kadai
  datasource:
    url: jdbc:h2:file:./data/fintap;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

app:
  bank-name: ABC Bank
  product-name: Digi Kadai
  demo-pin: "1234"

integrations:
  public-base-url: ${PUBLIC_BASE_URL:http://localhost:8080}
  allow-runtime-credentials: ${ALLOW_RUNTIME_CREDENTIALS:false}
  ondc:
    enabled: ${ONDC_ENABLED:true}
    subscriber-id: ${ONDC_SUBSCRIBER_ID:fintap.local}
    unique-key-id: ${ONDC_UNIQUE_KEY_ID:ukid-1}
    subscriber-url: ${ONDC_SUBSCRIBER_URL:http://localhost:8080/protocol/v1}
    signing-private-key: ${ONDC_SIGNING_PRIVATE_KEY:}
    signing-public-key: ${ONDC_SIGNING_PUBLIC_KEY:}
    encryption-private-key: ${ONDC_ENCRYPTION_PRIVATE_KEY:}
    encryption-public-key: ${ONDC_ENCRYPTION_PUBLIC_KEY:}
    registry-encryption-public-key: ${ONDC_REGISTRY_ENCRYPTION_PUBLIC_KEY:}
    site-verification-token: ${ONDC_SITE_VERIFICATION_TOKEN:}
    verify-incoming: ${ONDC_VERIFY_INCOMING:true}
    allow-http-callbacks: ${ONDC_ALLOW_HTTP_CALLBACKS:false}
    registry-url: ${ONDC_REGISTRY_URL:https://preprod.registry.ondc.org}
    gateway-url: ${ONDC_GATEWAY_URL:https://preprod.gateway.ondc.org}
    mock-bpp-url: ${ONDC_MOCK_BPP_URL:https://mock.ondc.org/api/b2b/bpp}
    domain: ${ONDC_DOMAIN:ONDC:RET10}
    city: ${ONDC_CITY:std:080}
    core-version: "1.2.0"
    bpp-id: ${ONDC_BPP_ID:}
    bpp-uri: ${ONDC_BPP_URI:http://localhost:8080/protocol/v1}
    country: IND
  mastercard:
    gateway-enabled: ${MC_GATEWAY_ENABLED:true}
    gateway-base-url: ${MC_GATEWAY_URL:https://test-gateway.mastercard.com}
    merchant-id: ${MC_MERCHANT_ID:}
    api-password: ${MC_API_PASSWORD:}
    api-version: ${MC_API_VERSION:100}
    currency: INR
    checkout-script-url: ${MC_CHECKOUT_SCRIPT_URL:}
    developers-enabled: ${MC_DEV_ENABLED:true}
    developers-base-url: ${MC_DEV_BASE_URL:https://sandbox.api.mastercard.com}
    consumer-key: ${MC_CONSUMER_KEY:}
    keystore-path: ${MC_KEYSTORE_PATH:C:\\Users\\SA10732542\\Downloads\\ganesanmail2me_Sandbox_API_Keys\\ganesanmail2me-sandbox.p12}
    keystore-password: ${MC_KEYSTORE_PASSWORD:}
    key-alias: ${MC_KEY_ALIAS:}
  razorpay:
    enabled: ${RAZORPAY_ENABLED:true}
    key-id: ${RAZORPAY_KEY_ID:}
    key-secret: ${RAZORPAY_KEY_SECRET:}
    base-url: ${RAZORPAY_BASE_URL:https://api.razorpay.com}
